### ISSUE TITLE
Parallel processing for lhr

### ISSUE THREAD

**Issue by davepallot** [ASKAP-EMUCat/emucat_components#4]
Hi Yjan,
I was reprocessing some mosaic data for a particular SER and noticed that lhr was taking some time to complete (~1M allwise source and ~70k components). I decided to have a quick look at the code and found some 'low hanging fruit' in regards to parallelizing some code i.e farm out some processing to multicore cpu machines then rejoin the data when complete. I added some changes to the code the lhr branch (https://github.com/ASKAP-EMUCat/emucat_components/tree/lhr). Here are the commits: https://github.com/ASKAP-EMUCat/emucat_components/commit/52da91938ec0e09c15fedec54fa8ea195b006e03

I checked the output results from the original with the new code and noticed no changes to the results. However it would be good to have a quick review of the code to see if I have done something wrong (technically and/or conceptually). If you have time (no rush) is it ok to have a quick look and if you are happy I can merge into the master?

Thanks 
Dave

**Comment by ygordon** [comment]
That's great, I should have some time to look at these this week and get back to you -- feel free to poke me if you haven't heard by Friday

**Comment by davepallot** [comment]
@ygordon did you have a chance to have a quick look at this? If you are happy I can merge these changes.

**Comment by ygordon** [comment]
Sorry for the delay (and thanks for the reminder) @davepallot. Yep, these look okay to me, and as the output is the same then I'm happy.

**Comment by davepallot** [comment]
Thanks @ygordon, ive merged it in.
